version: "3"

services:
  mongo-db:
    image: mongo
    restart: unless-stopped
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  crobora-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: us-central1-docker.pkg.dev/ter-2021/ter-2021-repo/crobora-backend:latest
    restart: unless-stopped
    container_name: crobora-backend
    depends_on:
      - mongo-db
    ports:
      - "3000:3000"
    environment:
      - DB_HOST_NAME=mongo-db
      - DB_PORT=27017
      - DB_NAME=admin

  web-app:
    build: 
      context: ./Front-end/CROBORA-App
      dockerfile: Dockerfile
    image: us-central1-docker.pkg.dev/ter-2021/ter-2021-repo/crobora-front-end:latest
    restart: unless-stopped
    container_name: crobora-web
    depends_on: 
      - crobora-backend
    ports:
      - "80:80"



volumes:
  mongo-data: