version: "3.8"

services:
  mongo-db:
    image: mongo
    restart: unless-stopped
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: crobora-backend:latest
    restart: unless-stopped
    container_name: crobora-backend
    depends_on:
      - mongo-db
    ports:
      - "3000:3000"
    environment:
      - DB_HOST_NAME=mongo-db
      - DB_PORT=27017


volumes:
  mongo-data: